# 数据源配置
spring:
  quartz:
    #quartz相关属性配置
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
            misfireThreshold: 12000
          #线程池配置
          threadPool:
            #实现的类名
            class: org.quartz.simpl.SimpleThreadPool
            #线程数量
            threadCount: 3
            #线程优先级
            threadPriority: 5
            #自创建父线程
            threadsInheritContextClassLoaderOfInitializingThread: true
    #数据库方式
    job-store-type: jdbc
# mybaits-plus配置
mybatis-plus:
  # MyBatis Mapper所对应的XML文件位置 : 注意,使用mybatis-plus时,它需要扫描到所有的Mapper.xml文件,否则baomidaou就会找不到mapper xml方法
  mapper-locations: classpath*:/mybatis/**/*Mapper.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      # 主键类型 0:数据库ID自增 1.未定义 2.用户输入 3 id_worker 4.uuid 5.id_worker字符串表示
      id-type: AUTO
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: NOT_NULL
      # 默认数据库表下划线命名
      table-underline: true